### PR TITLE
Fix tokenization of hyphenated compound words

### LINKED ISSUE #114: Hyphenated compound words are wrongly tokenized as negated
- The tokenizer wrongly counts subterms in compound words as negated
- `64-bit` is parsed as `64 -bit` and therefore excludes any hit of `bit`
- Surfaced by @discordier in [this pr comment](https://github.com/loupe-php/loupe/pull/104#issuecomment-2498402776)

### PR DESCRIPTION
**Pull request by daun**
- Make sure we're only marking words as negated if they aren't part of compound words
- Added tests to avoid regressions
- Fixes #114

### CODE REVIEW

**Comment by Toflar** [comment]
`develop` will be 0.9, this is a bug in 0.8 so should go to `main`. But the fix looks correct to me, let me rebase myself :)

**Comment by discordier** [comment]
Not there yet, see my PR to your branch which adds additional (functional) test.

**Comment by daun** [comment]
@discordier Which PR? [This commit](https://github.com/loupe-php/loupe/commit/a530ae5962bdf25c089f54a80e5361ac0d7eecd5) by chance? Looks relevant.

**Comment by discordier** [comment]
> @discordier Which PR? [This commit](https://github.com/loupe-php/loupe/commit/a530ae5962bdf25c089f54a80e5361ac0d7eecd5) by chance? Looks relevant.

https://github.com/daun/loupe/pull/1

**Comment by Toflar** [comment]
I won't rebase myself then :D

**Comment by discordier** [comment]
> I won't rebase myself then :D

Might be a good idea :D

**Comment by daun** [comment]
Will try and rebase from here...

**Comment by daun** [comment]
@Toflar The `IntlBreakIterator` class is fascianting, it's not properly documented in the official php docs and there's no example code to speak of on GitHub. How did you even find that? 🤠

**Comment by daun** [comment]
@Toflar Do we currently care about [CJK](https://de.wikipedia.org/wiki/CJK) codepoints? Might make this a lot more complex. Dealing with words and spaces is tricky enough...

**Comment by daun** [comment]
@Toflar Good to go from my end. Added tests and fixed the issue with the tokenizer. This strongly hinges on the concept of whitespace to distinguish negation by`-` from compounding by `-`. That's generally fine for Latin/European stuff, but I'm woefully uninformed about the CJK equivalents of this. Probably best to fix this for now and worry about the complexities later?

**Comment by Toflar** [comment]
> @Toflar The `IntlBreakIterator` class is fascianting, it's not properly documented in the official php docs and there's no example code to speak of on GitHub. How did you even find that? 🤠

Working with PHP for over 15 years and growing up in a country speaking multiple languages, I guess 🙈 ICU and Intl are worth a deep-dive anyway 😊 

> This strongly hinges on the concept of whitespace to distinguish negation by`-` from compounding by `-`. That's generally fine for Latin/European stuff, but I'm woefully uninformed about the CJK equivalents of this. Probably best to merge this for now and worry about the complexities later?

Yeah, not super happy about this but the problem is that we would also need CJK examples (and knowledge) of how they should be tokenized properly. 
Are the added tests to `TokenizerTest` covering all the use cases provided by the functional tests by @discordier? While I think the functional tests are valuable anyway, I would still like to have all the problematic cases covered in `TokenizerTest` so they are isolated and changes to the `Tokenizer` class can be verified easily without having to run the entire functional testsuite.

**Review by Toflar — APPROVED** [review]

**Comment by Toflar** [comment]
I guess we'll just leave this as is because we know it's correct for latin based languages. We can still improve the Tokenizer for other languages but those contributions likely have to come from the respective native speaking community 😊 
Released as 0.8.1, thanks for the quick fix @daun!

**Pull request merged**
